/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: inventory.proto */

#ifndef PROTOBUF_C_inventory_2eproto__INCLUDED
#define PROTOBUF_C_inventory_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "item.pb-c.h"

typedef struct Inventory Inventory;


/* --- enums --- */


/* --- messages --- */

struct  Inventory
{
  ProtobufCMessage base;
  int32_t capacity;
  size_t n_items;
  Item **items;
};
#define INVENTORY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&inventory__descriptor) \
    , 0, 0,NULL }


/* Inventory methods */
void   inventory__init
                     (Inventory         *message);
size_t inventory__get_packed_size
                     (const Inventory   *message);
size_t inventory__pack
                     (const Inventory   *message,
                      uint8_t             *out);
size_t inventory__pack_to_buffer
                     (const Inventory   *message,
                      ProtobufCBuffer     *buffer);
Inventory *
       inventory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   inventory__free_unpacked
                     (Inventory *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Inventory_Closure)
                 (const Inventory *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor inventory__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_inventory_2eproto__INCLUDED */
