/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: inventory.proto */

#ifndef PROTOBUF_C_inventory_2eproto__INCLUDED
#define PROTOBUF_C_inventory_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "item.pb-c.h"

typedef struct Game__Inventory Game__Inventory;


/* --- enums --- */


/* --- messages --- */

struct  Game__Inventory
{
  ProtobufCMessage base;
  int32_t capacity;
  size_t n_items;
  Game__Item **items;
};
#define GAME__INVENTORY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__inventory__descriptor) \
    , 0, 0,NULL }


/* Game__Inventory methods */
void   game__inventory__init
                     (Game__Inventory         *message);
size_t game__inventory__get_packed_size
                     (const Game__Inventory   *message);
size_t game__inventory__pack
                     (const Game__Inventory   *message,
                      uint8_t             *out);
size_t game__inventory__pack_to_buffer
                     (const Game__Inventory   *message,
                      ProtobufCBuffer     *buffer);
Game__Inventory *
       game__inventory__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__inventory__free_unpacked
                     (Game__Inventory *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__Inventory_Closure)
                 (const Game__Inventory *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor game__inventory__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_inventory_2eproto__INCLUDED */
