/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: item.proto */

#ifndef PROTOBUF_C_item_2eproto__INCLUDED
#define PROTOBUF_C_item_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Item Item;


/* --- enums --- */

typedef enum _ItemType {
  ITEM_TYPE__WEAPON = 0,
  ITEM_TYPE__ARMOUR = 1,
  ITEM_TYPE__RING = 2,
  ITEM_TYPE__BOOK = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ITEM_TYPE)
} ItemType;

/* --- messages --- */

struct  Item
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  float weight;
  ItemType type;
};
#define ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&item__descriptor) \
    , 0, NULL, 0, ITEM_TYPE__WEAPON }


/* Item methods */
void   item__init
                     (Item         *message);
size_t item__get_packed_size
                     (const Item   *message);
size_t item__pack
                     (const Item   *message,
                      uint8_t             *out);
size_t item__pack_to_buffer
                     (const Item   *message,
                      ProtobufCBuffer     *buffer);
Item *
       item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   item__free_unpacked
                     (Item *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Item_Closure)
                 (const Item *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    item_type__descriptor;
extern const ProtobufCMessageDescriptor item__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_item_2eproto__INCLUDED */
