/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: item.proto */

#ifndef PROTOBUF_C_item_2eproto__INCLUDED
#define PROTOBUF_C_item_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Game__Item Game__Item;


/* --- enums --- */

typedef enum _Game__Item__ItemType {
  GAME__ITEM__ITEM_TYPE__WEAPON = 0,
  GAME__ITEM__ITEM_TYPE__ARMOUR = 1,
  GAME__ITEM__ITEM_TYPE__RING = 2,
  GAME__ITEM__ITEM_TYPE__BOOK = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GAME__ITEM__ITEM_TYPE)
} Game__Item__ItemType;

/* --- messages --- */

struct  Game__Item
{
  ProtobufCMessage base;
  int32_t id;
  char *name;
  float weight;
  Game__Item__ItemType type;
};
#define GAME__ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__item__descriptor) \
    , 0, NULL, 0, GAME__ITEM__ITEM_TYPE__WEAPON }


/* Game__Item methods */
void   game__item__init
                     (Game__Item         *message);
size_t game__item__get_packed_size
                     (const Game__Item   *message);
size_t game__item__pack
                     (const Game__Item   *message,
                      uint8_t             *out);
size_t game__item__pack_to_buffer
                     (const Game__Item   *message,
                      ProtobufCBuffer     *buffer);
Game__Item *
       game__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__item__free_unpacked
                     (Game__Item *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__Item_Closure)
                 (const Game__Item *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor game__item__descriptor;
extern const ProtobufCEnumDescriptor    game__item__item_type__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_item_2eproto__INCLUDED */
