/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testproto2.proto */

#ifndef PROTOBUF_C_testproto2_2eproto__INCLUDED
#define PROTOBUF_C_testproto2_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Testp2__Scalars Testp2__Scalars;
typedef struct Testp2__Outer Testp2__Outer;
typedef struct Testp2__Outer__Middle Testp2__Outer__Middle;
typedef struct Testp2__Outer__Middle__Inner Testp2__Outer__Middle__Inner;
typedef struct Testp2__Basic Testp2__Basic;
typedef struct Testp2__Container Testp2__Container;
typedef struct Testp2__Container__BasicMapEntry Testp2__Container__BasicMapEntry;
typedef struct Testp2__Container__StringMapEntry Testp2__Container__StringMapEntry;


/* --- enums --- */

typedef enum _Testp2__Language {
  TESTP2__LANGUAGE__LANGUAGE_LUA = 0,
  TESTP2__LANGUAGE__LANGUAGE_CPP = 1,
  TESTP2__LANGUAGE__LANGUAGE_JAVA = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TESTP2__LANGUAGE)
} Testp2__Language;

/* --- messages --- */

/*
 * 
 * Multi-line comment
 */
struct  Testp2__Scalars
{
  ProtobufCMessage base;
  /*
   * all proto3 scalar values
   */
  int32_t i32;
  int64_t i64;
  uint32_t ui32;
  uint64_t ui64;
  int32_t si32;
  int64_t si64;
  uint32_t fix32;
  uint64_t fix64;
  int32_t sfix32;
  int64_t sfix64;
  protobuf_c_boolean b;
  /*
   * comment
   */
  char *s;
  ProtobufCBinaryData bytes;
  double d;
  float f;
};
#define TESTP2__SCALARS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__scalars__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NULL, {0,NULL}, 0, 0 }


struct  Testp2__Outer__Middle__Inner
{
  ProtobufCMessage base;
  char *text;
};
#define TESTP2__OUTER__MIDDLE__INNER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__outer__middle__inner__descriptor) \
    , NULL }


struct  Testp2__Outer__Middle
{
  ProtobufCMessage base;
  char *text;
  Testp2__Outer__Middle__Inner *inner;
};
#define TESTP2__OUTER__MIDDLE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__outer__middle__descriptor) \
    , NULL, NULL }


struct  Testp2__Outer
{
  ProtobufCMessage base;
  char *text;
  Testp2__Outer__Middle *middle;
};
#define TESTP2__OUTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__outer__descriptor) \
    , NULL, NULL }


struct  Testp2__Basic
{
  ProtobufCMessage base;
  char *s;
  int32_t i;
  Testp2__Language lang;
};
#define TESTP2__BASIC__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__basic__descriptor) \
    , NULL, 0, TESTP2__LANGUAGE__LANGUAGE_LUA }


struct  Testp2__Container__BasicMapEntry
{
  ProtobufCMessage base;
  char *key;
  Testp2__Basic *value;
};
#define TESTP2__CONTAINER__BASIC_MAP_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__container__basic_map_entry__descriptor) \
    , NULL, NULL }


struct  Testp2__Container__StringMapEntry
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define TESTP2__CONTAINER__STRING_MAP_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__container__string_map_entry__descriptor) \
    , NULL, NULL }


struct  Testp2__Container
{
  ProtobufCMessage base;
  size_t n_basic_map;
  Testp2__Container__BasicMapEntry **basic_map;
  size_t n_string_map;
  Testp2__Container__StringMapEntry **string_map;
  size_t n_repeated_string;
  char **repeated_string;
  size_t n_repeated_basic;
  Testp2__Basic **repeated_basic;
  char *optional_string1;
  char *optional_string2;
  Testp2__Basic *optional_basic1;
  Testp2__Basic *optional_basic2;
};
#define TESTP2__CONTAINER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&testp2__container__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, NULL, NULL, NULL }


/* Testp2__Scalars methods */
void   testp2__scalars__init
                     (Testp2__Scalars         *message);
size_t testp2__scalars__get_packed_size
                     (const Testp2__Scalars   *message);
size_t testp2__scalars__pack
                     (const Testp2__Scalars   *message,
                      uint8_t             *out);
size_t testp2__scalars__pack_to_buffer
                     (const Testp2__Scalars   *message,
                      ProtobufCBuffer     *buffer);
Testp2__Scalars *
       testp2__scalars__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   testp2__scalars__free_unpacked
                     (Testp2__Scalars *message,
                      ProtobufCAllocator *allocator);
/* Testp2__Outer__Middle__Inner methods */
void   testp2__outer__middle__inner__init
                     (Testp2__Outer__Middle__Inner         *message);
/* Testp2__Outer__Middle methods */
void   testp2__outer__middle__init
                     (Testp2__Outer__Middle         *message);
/* Testp2__Outer methods */
void   testp2__outer__init
                     (Testp2__Outer         *message);
size_t testp2__outer__get_packed_size
                     (const Testp2__Outer   *message);
size_t testp2__outer__pack
                     (const Testp2__Outer   *message,
                      uint8_t             *out);
size_t testp2__outer__pack_to_buffer
                     (const Testp2__Outer   *message,
                      ProtobufCBuffer     *buffer);
Testp2__Outer *
       testp2__outer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   testp2__outer__free_unpacked
                     (Testp2__Outer *message,
                      ProtobufCAllocator *allocator);
/* Testp2__Basic methods */
void   testp2__basic__init
                     (Testp2__Basic         *message);
size_t testp2__basic__get_packed_size
                     (const Testp2__Basic   *message);
size_t testp2__basic__pack
                     (const Testp2__Basic   *message,
                      uint8_t             *out);
size_t testp2__basic__pack_to_buffer
                     (const Testp2__Basic   *message,
                      ProtobufCBuffer     *buffer);
Testp2__Basic *
       testp2__basic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   testp2__basic__free_unpacked
                     (Testp2__Basic *message,
                      ProtobufCAllocator *allocator);
/* Testp2__Container__BasicMapEntry methods */
void   testp2__container__basic_map_entry__init
                     (Testp2__Container__BasicMapEntry         *message);
/* Testp2__Container__StringMapEntry methods */
void   testp2__container__string_map_entry__init
                     (Testp2__Container__StringMapEntry         *message);
/* Testp2__Container methods */
void   testp2__container__init
                     (Testp2__Container         *message);
size_t testp2__container__get_packed_size
                     (const Testp2__Container   *message);
size_t testp2__container__pack
                     (const Testp2__Container   *message,
                      uint8_t             *out);
size_t testp2__container__pack_to_buffer
                     (const Testp2__Container   *message,
                      ProtobufCBuffer     *buffer);
Testp2__Container *
       testp2__container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   testp2__container__free_unpacked
                     (Testp2__Container *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Testp2__Scalars_Closure)
                 (const Testp2__Scalars *message,
                  void *closure_data);
typedef void (*Testp2__Outer__Middle__Inner_Closure)
                 (const Testp2__Outer__Middle__Inner *message,
                  void *closure_data);
typedef void (*Testp2__Outer__Middle_Closure)
                 (const Testp2__Outer__Middle *message,
                  void *closure_data);
typedef void (*Testp2__Outer_Closure)
                 (const Testp2__Outer *message,
                  void *closure_data);
typedef void (*Testp2__Basic_Closure)
                 (const Testp2__Basic *message,
                  void *closure_data);
typedef void (*Testp2__Container__BasicMapEntry_Closure)
                 (const Testp2__Container__BasicMapEntry *message,
                  void *closure_data);
typedef void (*Testp2__Container__StringMapEntry_Closure)
                 (const Testp2__Container__StringMapEntry *message,
                  void *closure_data);
typedef void (*Testp2__Container_Closure)
                 (const Testp2__Container *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    testp2__language__descriptor;
extern const ProtobufCMessageDescriptor testp2__scalars__descriptor;
extern const ProtobufCMessageDescriptor testp2__outer__descriptor;
extern const ProtobufCMessageDescriptor testp2__outer__middle__descriptor;
extern const ProtobufCMessageDescriptor testp2__outer__middle__inner__descriptor;
extern const ProtobufCMessageDescriptor testp2__basic__descriptor;
extern const ProtobufCMessageDescriptor testp2__container__descriptor;
extern const ProtobufCMessageDescriptor testp2__container__basic_map_entry__descriptor;
extern const ProtobufCMessageDescriptor testp2__container__string_map_entry__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_testproto2_2eproto__INCLUDED */
