function init(self)
	local person = {
		name = "Bob",
		email = "bob@acme.com",
		id = 1
	}
	-- serialize the Lua table to a Person message
	local msg = proto.encode_person(person)
	assert(msg)
	assert(#msg == 21)

	-- decode the binary message back to a Lua table
	local decoded = proto.decode_person(msg)
	pprint(decoded)
	assert(decoded.id == person.id)
	assert(decoded.name == person.name)
	assert(decoded.email == person.email)
end
