/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: item.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "item.pb-c.h"
void   game__item__init
                     (Game__Item         *message)
{
  static const Game__Item init_value = GAME__ITEM__INIT;
  *message = init_value;
}
size_t game__item__get_packed_size
                     (const Game__Item *message)
{
  assert(message->base.descriptor == &game__item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__item__pack
                     (const Game__Item *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &game__item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__item__pack_to_buffer
                     (const Game__Item *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &game__item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__Item *
       game__item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__Item *)
     protobuf_c_message_unpack (&game__item__descriptor,
                                allocator, len, data);
}
void   game__item__free_unpacked
                     (Game__Item *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &game__item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue game__item__item_type__enum_values_by_number[4] =
{
  { "WEAPON", "GAME__ITEM__ITEM_TYPE__WEAPON", 0 },
  { "ARMOUR", "GAME__ITEM__ITEM_TYPE__ARMOUR", 1 },
  { "RING", "GAME__ITEM__ITEM_TYPE__RING", 2 },
  { "BOOK", "GAME__ITEM__ITEM_TYPE__BOOK", 3 },
};
static const ProtobufCIntRange game__item__item_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex game__item__item_type__enum_values_by_name[4] =
{
  { "ARMOUR", 1 },
  { "BOOK", 3 },
  { "RING", 2 },
  { "WEAPON", 0 },
};
const ProtobufCEnumDescriptor game__item__item_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Game.Item.ItemType",
  "ItemType",
  "Game__Item__ItemType",
  "Game",
  4,
  game__item__item_type__enum_values_by_number,
  4,
  game__item__item_type__enum_values_by_name,
  1,
  game__item__item_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor game__item__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Game__Item, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Game__Item, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Game__Item, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Game__Item, type),
    &game__item__item_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__item__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  3,   /* field[3] = type */
  2,   /* field[2] = weight */
};
static const ProtobufCIntRange game__item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor game__item__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Game.Item",
  "Item",
  "Game__Item",
  "Game",
  sizeof(Game__Item),
  4,
  game__item__field_descriptors,
  game__item__field_indices_by_name,
  1,  game__item__number_ranges,
  (ProtobufCMessageInit) game__item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
