/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testproto3.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "testproto3.pb-c.h"
void   testp3__scalars__init
                     (Testp3__Scalars         *message)
{
  static const Testp3__Scalars init_value = TESTP3__SCALARS__INIT;
  *message = init_value;
}
size_t testp3__scalars__get_packed_size
                     (const Testp3__Scalars *message)
{
  assert(message->base.descriptor == &testp3__scalars__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp3__scalars__pack
                     (const Testp3__Scalars *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp3__scalars__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp3__scalars__pack_to_buffer
                     (const Testp3__Scalars *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp3__scalars__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp3__Scalars *
       testp3__scalars__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp3__Scalars *)
     protobuf_c_message_unpack (&testp3__scalars__descriptor,
                                allocator, len, data);
}
void   testp3__scalars__free_unpacked
                     (Testp3__Scalars *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp3__scalars__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp3__outer__middle__inner__init
                     (Testp3__Outer__Middle__Inner         *message)
{
  static const Testp3__Outer__Middle__Inner init_value = TESTP3__OUTER__MIDDLE__INNER__INIT;
  *message = init_value;
}
void   testp3__outer__middle__init
                     (Testp3__Outer__Middle         *message)
{
  static const Testp3__Outer__Middle init_value = TESTP3__OUTER__MIDDLE__INIT;
  *message = init_value;
}
void   testp3__outer__init
                     (Testp3__Outer         *message)
{
  static const Testp3__Outer init_value = TESTP3__OUTER__INIT;
  *message = init_value;
}
size_t testp3__outer__get_packed_size
                     (const Testp3__Outer *message)
{
  assert(message->base.descriptor == &testp3__outer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp3__outer__pack
                     (const Testp3__Outer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp3__outer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp3__outer__pack_to_buffer
                     (const Testp3__Outer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp3__outer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp3__Outer *
       testp3__outer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp3__Outer *)
     protobuf_c_message_unpack (&testp3__outer__descriptor,
                                allocator, len, data);
}
void   testp3__outer__free_unpacked
                     (Testp3__Outer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp3__outer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp3__basic__init
                     (Testp3__Basic         *message)
{
  static const Testp3__Basic init_value = TESTP3__BASIC__INIT;
  *message = init_value;
}
size_t testp3__basic__get_packed_size
                     (const Testp3__Basic *message)
{
  assert(message->base.descriptor == &testp3__basic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp3__basic__pack
                     (const Testp3__Basic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp3__basic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp3__basic__pack_to_buffer
                     (const Testp3__Basic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp3__basic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp3__Basic *
       testp3__basic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp3__Basic *)
     protobuf_c_message_unpack (&testp3__basic__descriptor,
                                allocator, len, data);
}
void   testp3__basic__free_unpacked
                     (Testp3__Basic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp3__basic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp3__container__basic_map_entry__init
                     (Testp3__Container__BasicMapEntry         *message)
{
  static const Testp3__Container__BasicMapEntry init_value = TESTP3__CONTAINER__BASIC_MAP_ENTRY__INIT;
  *message = init_value;
}
void   testp3__container__string_map_entry__init
                     (Testp3__Container__StringMapEntry         *message)
{
  static const Testp3__Container__StringMapEntry init_value = TESTP3__CONTAINER__STRING_MAP_ENTRY__INIT;
  *message = init_value;
}
void   testp3__container__init
                     (Testp3__Container         *message)
{
  static const Testp3__Container init_value = TESTP3__CONTAINER__INIT;
  *message = init_value;
}
size_t testp3__container__get_packed_size
                     (const Testp3__Container *message)
{
  assert(message->base.descriptor == &testp3__container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp3__container__pack
                     (const Testp3__Container *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp3__container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp3__container__pack_to_buffer
                     (const Testp3__Container *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp3__container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp3__Container *
       testp3__container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp3__Container *)
     protobuf_c_message_unpack (&testp3__container__descriptor,
                                allocator, len, data);
}
void   testp3__container__free_unpacked
                     (Testp3__Container *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp3__container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor testp3__scalars__field_descriptors[15] =
{
  {
    "i32",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, i32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i64",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, i64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui32",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, ui32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui64",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, ui64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si32",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, si32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si64",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, si64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fix32",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, fix32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fix64",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, fix64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfix32",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, sfix32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfix64",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_SFIXED64,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, sfix64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, s),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Testp3__Scalars, f),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__scalars__field_indices_by_name[] = {
  10,   /* field[10] = b */
  12,   /* field[12] = bytes */
  13,   /* field[13] = d */
  14,   /* field[14] = f */
  6,   /* field[6] = fix32 */
  7,   /* field[7] = fix64 */
  0,   /* field[0] = i32 */
  1,   /* field[1] = i64 */
  11,   /* field[11] = s */
  8,   /* field[8] = sfix32 */
  9,   /* field[9] = sfix64 */
  4,   /* field[4] = si32 */
  5,   /* field[5] = si64 */
  2,   /* field[2] = ui32 */
  3,   /* field[3] = ui64 */
};
static const ProtobufCIntRange testp3__scalars__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor testp3__scalars__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Scalars",
  "Scalars",
  "Testp3__Scalars",
  "testp3",
  sizeof(Testp3__Scalars),
  15,
  testp3__scalars__field_descriptors,
  testp3__scalars__field_indices_by_name,
  1,  testp3__scalars__number_ranges,
  (ProtobufCMessageInit) testp3__scalars__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__outer__middle__inner__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Outer__Middle__Inner, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__outer__middle__inner__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp3__outer__middle__inner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor testp3__outer__middle__inner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Outer.Middle.Inner",
  "Inner",
  "Testp3__Outer__Middle__Inner",
  "testp3",
  sizeof(Testp3__Outer__Middle__Inner),
  1,
  testp3__outer__middle__inner__field_descriptors,
  testp3__outer__middle__inner__field_indices_by_name,
  1,  testp3__outer__middle__inner__number_ranges,
  (ProtobufCMessageInit) testp3__outer__middle__inner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__outer__middle__field_descriptors[2] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Outer__Middle, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp3__Outer__Middle, inner),
    &testp3__outer__middle__inner__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__outer__middle__field_indices_by_name[] = {
  1,   /* field[1] = inner */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp3__outer__middle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp3__outer__middle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Outer.Middle",
  "Middle",
  "Testp3__Outer__Middle",
  "testp3",
  sizeof(Testp3__Outer__Middle),
  2,
  testp3__outer__middle__field_descriptors,
  testp3__outer__middle__field_indices_by_name,
  1,  testp3__outer__middle__number_ranges,
  (ProtobufCMessageInit) testp3__outer__middle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__outer__field_descriptors[2] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Outer, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "middle",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp3__Outer, middle),
    &testp3__outer__middle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__outer__field_indices_by_name[] = {
  1,   /* field[1] = middle */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp3__outer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp3__outer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Outer",
  "Outer",
  "Testp3__Outer",
  "testp3",
  sizeof(Testp3__Outer),
  2,
  testp3__outer__field_descriptors,
  testp3__outer__field_indices_by_name,
  1,  testp3__outer__number_ranges,
  (ProtobufCMessageInit) testp3__outer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__basic__field_descriptors[3] =
{
  {
    "s",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Basic, s),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Testp3__Basic, i),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lang",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Testp3__Basic, lang),
    &testp3__language__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__basic__field_indices_by_name[] = {
  1,   /* field[1] = i */
  2,   /* field[2] = lang */
  0,   /* field[0] = s */
};
static const ProtobufCIntRange testp3__basic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor testp3__basic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Basic",
  "Basic",
  "Testp3__Basic",
  "testp3",
  sizeof(Testp3__Basic),
  3,
  testp3__basic__field_descriptors,
  testp3__basic__field_indices_by_name,
  1,  testp3__basic__number_ranges,
  (ProtobufCMessageInit) testp3__basic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__container__basic_map_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Container__BasicMapEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp3__Container__BasicMapEntry, value),
    &testp3__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__container__basic_map_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange testp3__container__basic_map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp3__container__basic_map_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Container.BasicMapEntry",
  "BasicMapEntry",
  "Testp3__Container__BasicMapEntry",
  "testp3",
  sizeof(Testp3__Container__BasicMapEntry),
  2,
  testp3__container__basic_map_entry__field_descriptors,
  testp3__container__basic_map_entry__field_indices_by_name,
  1,  testp3__container__basic_map_entry__number_ranges,
  (ProtobufCMessageInit) testp3__container__basic_map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__container__string_map_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Container__StringMapEntry, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp3__Container__StringMapEntry, value),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__container__string_map_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange testp3__container__string_map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp3__container__string_map_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Container.StringMapEntry",
  "StringMapEntry",
  "Testp3__Container__StringMapEntry",
  "testp3",
  sizeof(Testp3__Container__StringMapEntry),
  2,
  testp3__container__string_map_entry__field_descriptors,
  testp3__container__string_map_entry__field_indices_by_name,
  1,  testp3__container__string_map_entry__number_ranges,
  (ProtobufCMessageInit) testp3__container__string_map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp3__container__field_descriptors[4] =
{
  {
    "basic_map",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp3__Container, n_basic_map),
    offsetof(Testp3__Container, basic_map),
    &testp3__container__basic_map_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_map",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp3__Container, n_string_map),
    offsetof(Testp3__Container, string_map),
    &testp3__container__string_map_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeated_string",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Testp3__Container, n_repeated_string),
    offsetof(Testp3__Container, repeated_string),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeated_basic",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp3__Container, n_repeated_basic),
    offsetof(Testp3__Container, repeated_basic),
    &testp3__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp3__container__field_indices_by_name[] = {
  0,   /* field[0] = basic_map */
  3,   /* field[3] = repeated_basic */
  2,   /* field[2] = repeated_string */
  1,   /* field[1] = string_map */
};
static const ProtobufCIntRange testp3__container__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor testp3__container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp3.Container",
  "Container",
  "Testp3__Container",
  "testp3",
  sizeof(Testp3__Container),
  4,
  testp3__container__field_descriptors,
  testp3__container__field_indices_by_name,
  1,  testp3__container__number_ranges,
  (ProtobufCMessageInit) testp3__container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue testp3__language__enum_values_by_number[3] =
{
  { "LANGUAGE_LUA", "TESTP3__LANGUAGE__LANGUAGE_LUA", 0 },
  { "LANGUAGE_CPP", "TESTP3__LANGUAGE__LANGUAGE_CPP", 1 },
  { "LANGUAGE_JAVA", "TESTP3__LANGUAGE__LANGUAGE_JAVA", 2 },
};
static const ProtobufCIntRange testp3__language__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex testp3__language__enum_values_by_name[3] =
{
  { "LANGUAGE_CPP", 1 },
  { "LANGUAGE_JAVA", 2 },
  { "LANGUAGE_LUA", 0 },
};
const ProtobufCEnumDescriptor testp3__language__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "testp3.Language",
  "Language",
  "Testp3__Language",
  "testp3",
  3,
  testp3__language__enum_values_by_number,
  3,
  testp3__language__enum_values_by_name,
  1,
  testp3__language__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
