/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: testproto2.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "testproto2.pb-c.h"
void   testp2__scalars__init
                     (Testp2__Scalars         *message)
{
  static const Testp2__Scalars init_value = TESTP2__SCALARS__INIT;
  *message = init_value;
}
size_t testp2__scalars__get_packed_size
                     (const Testp2__Scalars *message)
{
  assert(message->base.descriptor == &testp2__scalars__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp2__scalars__pack
                     (const Testp2__Scalars *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp2__scalars__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp2__scalars__pack_to_buffer
                     (const Testp2__Scalars *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp2__scalars__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp2__Scalars *
       testp2__scalars__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp2__Scalars *)
     protobuf_c_message_unpack (&testp2__scalars__descriptor,
                                allocator, len, data);
}
void   testp2__scalars__free_unpacked
                     (Testp2__Scalars *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp2__scalars__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp2__outer__middle__inner__init
                     (Testp2__Outer__Middle__Inner         *message)
{
  static const Testp2__Outer__Middle__Inner init_value = TESTP2__OUTER__MIDDLE__INNER__INIT;
  *message = init_value;
}
void   testp2__outer__middle__init
                     (Testp2__Outer__Middle         *message)
{
  static const Testp2__Outer__Middle init_value = TESTP2__OUTER__MIDDLE__INIT;
  *message = init_value;
}
void   testp2__outer__init
                     (Testp2__Outer         *message)
{
  static const Testp2__Outer init_value = TESTP2__OUTER__INIT;
  *message = init_value;
}
size_t testp2__outer__get_packed_size
                     (const Testp2__Outer *message)
{
  assert(message->base.descriptor == &testp2__outer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp2__outer__pack
                     (const Testp2__Outer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp2__outer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp2__outer__pack_to_buffer
                     (const Testp2__Outer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp2__outer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp2__Outer *
       testp2__outer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp2__Outer *)
     protobuf_c_message_unpack (&testp2__outer__descriptor,
                                allocator, len, data);
}
void   testp2__outer__free_unpacked
                     (Testp2__Outer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp2__outer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp2__basic__init
                     (Testp2__Basic         *message)
{
  static const Testp2__Basic init_value = TESTP2__BASIC__INIT;
  *message = init_value;
}
size_t testp2__basic__get_packed_size
                     (const Testp2__Basic *message)
{
  assert(message->base.descriptor == &testp2__basic__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp2__basic__pack
                     (const Testp2__Basic *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp2__basic__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp2__basic__pack_to_buffer
                     (const Testp2__Basic *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp2__basic__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp2__Basic *
       testp2__basic__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp2__Basic *)
     protobuf_c_message_unpack (&testp2__basic__descriptor,
                                allocator, len, data);
}
void   testp2__basic__free_unpacked
                     (Testp2__Basic *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp2__basic__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp2__container__basic_map_entry__init
                     (Testp2__Container__BasicMapEntry         *message)
{
  static const Testp2__Container__BasicMapEntry init_value = TESTP2__CONTAINER__BASIC_MAP_ENTRY__INIT;
  *message = init_value;
}
void   testp2__container__string_map_entry__init
                     (Testp2__Container__StringMapEntry         *message)
{
  static const Testp2__Container__StringMapEntry init_value = TESTP2__CONTAINER__STRING_MAP_ENTRY__INIT;
  *message = init_value;
}
void   testp2__container__init
                     (Testp2__Container         *message)
{
  static const Testp2__Container init_value = TESTP2__CONTAINER__INIT;
  *message = init_value;
}
size_t testp2__container__get_packed_size
                     (const Testp2__Container *message)
{
  assert(message->base.descriptor == &testp2__container__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp2__container__pack
                     (const Testp2__Container *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp2__container__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp2__container__pack_to_buffer
                     (const Testp2__Container *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp2__container__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp2__Container *
       testp2__container__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp2__Container *)
     protobuf_c_message_unpack (&testp2__container__descriptor,
                                allocator, len, data);
}
void   testp2__container__free_unpacked
                     (Testp2__Container *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp2__container__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   testp2__one_of__first_and_last__init
                     (Testp2__OneOf__FirstAndLast         *message)
{
  static const Testp2__OneOf__FirstAndLast init_value = TESTP2__ONE_OF__FIRST_AND_LAST__INIT;
  *message = init_value;
}
void   testp2__one_of__init
                     (Testp2__OneOf         *message)
{
  static const Testp2__OneOf init_value = TESTP2__ONE_OF__INIT;
  *message = init_value;
}
size_t testp2__one_of__get_packed_size
                     (const Testp2__OneOf *message)
{
  assert(message->base.descriptor == &testp2__one_of__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t testp2__one_of__pack
                     (const Testp2__OneOf *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &testp2__one_of__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t testp2__one_of__pack_to_buffer
                     (const Testp2__OneOf *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &testp2__one_of__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Testp2__OneOf *
       testp2__one_of__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Testp2__OneOf *)
     protobuf_c_message_unpack (&testp2__one_of__descriptor,
                                allocator, len, data);
}
void   testp2__one_of__free_unpacked
                     (Testp2__OneOf *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &testp2__one_of__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor testp2__scalars__field_descriptors[15] =
{
  {
    "i32",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, i32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i64",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, i64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui32",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, ui32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui64",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, ui64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si32",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, si32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si64",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SINT64,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, si64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fix32",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, fix32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fix64",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED64,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, fix64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfix32",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, sfix32),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sfix64",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_SFIXED64,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, sfix64),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bytes",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "d",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, d),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Testp2__Scalars, f),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__scalars__field_indices_by_name[] = {
  10,   /* field[10] = b */
  12,   /* field[12] = bytes */
  13,   /* field[13] = d */
  14,   /* field[14] = f */
  6,   /* field[6] = fix32 */
  7,   /* field[7] = fix64 */
  0,   /* field[0] = i32 */
  1,   /* field[1] = i64 */
  11,   /* field[11] = s */
  8,   /* field[8] = sfix32 */
  9,   /* field[9] = sfix64 */
  4,   /* field[4] = si32 */
  5,   /* field[5] = si64 */
  2,   /* field[2] = ui32 */
  3,   /* field[3] = ui64 */
};
static const ProtobufCIntRange testp2__scalars__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 15 }
};
const ProtobufCMessageDescriptor testp2__scalars__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Scalars",
  "Scalars",
  "Testp2__Scalars",
  "testp2",
  sizeof(Testp2__Scalars),
  15,
  testp2__scalars__field_descriptors,
  testp2__scalars__field_indices_by_name,
  1,  testp2__scalars__number_ranges,
  (ProtobufCMessageInit) testp2__scalars__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__outer__middle__inner__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Outer__Middle__Inner, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__outer__middle__inner__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp2__outer__middle__inner__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor testp2__outer__middle__inner__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Outer.Middle.Inner",
  "Inner",
  "Testp2__Outer__Middle__Inner",
  "testp2",
  sizeof(Testp2__Outer__Middle__Inner),
  1,
  testp2__outer__middle__inner__field_descriptors,
  testp2__outer__middle__inner__field_indices_by_name,
  1,  testp2__outer__middle__inner__number_ranges,
  (ProtobufCMessageInit) testp2__outer__middle__inner__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__outer__middle__field_descriptors[2] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Outer__Middle, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Outer__Middle, inner),
    &testp2__outer__middle__inner__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__outer__middle__field_indices_by_name[] = {
  1,   /* field[1] = inner */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp2__outer__middle__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp2__outer__middle__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Outer.Middle",
  "Middle",
  "Testp2__Outer__Middle",
  "testp2",
  sizeof(Testp2__Outer__Middle),
  2,
  testp2__outer__middle__field_descriptors,
  testp2__outer__middle__field_indices_by_name,
  1,  testp2__outer__middle__number_ranges,
  (ProtobufCMessageInit) testp2__outer__middle__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__outer__field_descriptors[2] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Outer, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "middle",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Outer, middle),
    &testp2__outer__middle__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__outer__field_indices_by_name[] = {
  1,   /* field[1] = middle */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange testp2__outer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp2__outer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Outer",
  "Outer",
  "Testp2__Outer",
  "testp2",
  sizeof(Testp2__Outer),
  2,
  testp2__outer__field_descriptors,
  testp2__outer__field_indices_by_name,
  1,  testp2__outer__number_ranges,
  (ProtobufCMessageInit) testp2__outer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__basic__field_descriptors[3] =
{
  {
    "s",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Basic, s),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Testp2__Basic, i),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lang",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Testp2__Basic, lang),
    &testp2__language__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__basic__field_indices_by_name[] = {
  1,   /* field[1] = i */
  2,   /* field[2] = lang */
  0,   /* field[0] = s */
};
static const ProtobufCIntRange testp2__basic__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor testp2__basic__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Basic",
  "Basic",
  "Testp2__Basic",
  "testp2",
  sizeof(Testp2__Basic),
  3,
  testp2__basic__field_descriptors,
  testp2__basic__field_indices_by_name,
  1,  testp2__basic__number_ranges,
  (ProtobufCMessageInit) testp2__basic__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__container__basic_map_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container__BasicMapEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container__BasicMapEntry, value),
    &testp2__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__container__basic_map_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange testp2__container__basic_map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp2__container__basic_map_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Container.BasicMapEntry",
  "BasicMapEntry",
  "Testp2__Container__BasicMapEntry",
  "testp2",
  sizeof(Testp2__Container__BasicMapEntry),
  2,
  testp2__container__basic_map_entry__field_descriptors,
  testp2__container__basic_map_entry__field_indices_by_name,
  1,  testp2__container__basic_map_entry__number_ranges,
  (ProtobufCMessageInit) testp2__container__basic_map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__container__string_map_entry__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container__StringMapEntry, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container__StringMapEntry, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__container__string_map_entry__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange testp2__container__string_map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp2__container__string_map_entry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Container.StringMapEntry",
  "StringMapEntry",
  "Testp2__Container__StringMapEntry",
  "testp2",
  sizeof(Testp2__Container__StringMapEntry),
  2,
  testp2__container__string_map_entry__field_descriptors,
  testp2__container__string_map_entry__field_indices_by_name,
  1,  testp2__container__string_map_entry__number_ranges,
  (ProtobufCMessageInit) testp2__container__string_map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__container__field_descriptors[8] =
{
  {
    "basic_map",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp2__Container, n_basic_map),
    offsetof(Testp2__Container, basic_map),
    &testp2__container__basic_map_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "string_map",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp2__Container, n_string_map),
    offsetof(Testp2__Container, string_map),
    &testp2__container__string_map_entry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeated_string",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Testp2__Container, n_repeated_string),
    offsetof(Testp2__Container, repeated_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeated_basic",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp2__Container, n_repeated_basic),
    offsetof(Testp2__Container, repeated_basic),
    &testp2__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional_string1",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container, optional_string1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional_string2",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container, optional_string2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional_basic1",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container, optional_basic1),
    &testp2__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "optional_basic2",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Testp2__Container, optional_basic2),
    &testp2__basic__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__container__field_indices_by_name[] = {
  0,   /* field[0] = basic_map */
  6,   /* field[6] = optional_basic1 */
  7,   /* field[7] = optional_basic2 */
  4,   /* field[4] = optional_string1 */
  5,   /* field[5] = optional_string2 */
  3,   /* field[3] = repeated_basic */
  2,   /* field[2] = repeated_string */
  1,   /* field[1] = string_map */
};
static const ProtobufCIntRange testp2__container__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor testp2__container__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.Container",
  "Container",
  "Testp2__Container",
  "testp2",
  sizeof(Testp2__Container),
  8,
  testp2__container__field_descriptors,
  testp2__container__field_indices_by_name,
  1,  testp2__container__number_ranges,
  (ProtobufCMessageInit) testp2__container__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__one_of__first_and_last__field_descriptors[2] =
{
  {
    "first",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__OneOf__FirstAndLast, first),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Testp2__OneOf__FirstAndLast, last),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__one_of__first_and_last__field_indices_by_name[] = {
  0,   /* field[0] = first */
  1,   /* field[1] = last */
};
static const ProtobufCIntRange testp2__one_of__first_and_last__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor testp2__one_of__first_and_last__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.OneOf.FirstAndLast",
  "FirstAndLast",
  "Testp2__OneOf__FirstAndLast",
  "testp2",
  sizeof(Testp2__OneOf__FirstAndLast),
  2,
  testp2__one_of__first_and_last__field_descriptors,
  testp2__one_of__first_and_last__field_indices_by_name,
  1,  testp2__one_of__first_and_last__number_ranges,
  (ProtobufCMessageInit) testp2__one_of__first_and_last__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor testp2__one_of__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Testp2__OneOf, oftest1_case),
    offsetof(Testp2__OneOf, name),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "first_and_last",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Testp2__OneOf, oftest1_case),
    offsetof(Testp2__OneOf, first_and_last),
    &testp2__one_of__first_and_last__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "foo",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Testp2__OneOf, oftest2_case),
    offsetof(Testp2__OneOf, foo),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bar",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Testp2__OneOf, oftest2_case),
    offsetof(Testp2__OneOf, bar),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned testp2__one_of__field_indices_by_name[] = {
  3,   /* field[3] = bar */
  1,   /* field[1] = first_and_last */
  2,   /* field[2] = foo */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange testp2__one_of__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor testp2__one_of__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "testp2.OneOf",
  "OneOf",
  "Testp2__OneOf",
  "testp2",
  sizeof(Testp2__OneOf),
  4,
  testp2__one_of__field_descriptors,
  testp2__one_of__field_indices_by_name,
  1,  testp2__one_of__number_ranges,
  (ProtobufCMessageInit) testp2__one_of__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue testp2__language__enum_values_by_number[3] =
{
  { "LANGUAGE_LUA", "TESTP2__LANGUAGE__LANGUAGE_LUA", 0 },
  { "LANGUAGE_CPP", "TESTP2__LANGUAGE__LANGUAGE_CPP", 1 },
  { "LANGUAGE_JAVA", "TESTP2__LANGUAGE__LANGUAGE_JAVA", 2 },
};
static const ProtobufCIntRange testp2__language__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex testp2__language__enum_values_by_name[3] =
{
  { "LANGUAGE_CPP", 1 },
  { "LANGUAGE_JAVA", 2 },
  { "LANGUAGE_LUA", 0 },
};
const ProtobufCEnumDescriptor testp2__language__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "testp2.Language",
  "Language",
  "Testp2__Language",
  "testp2",
  3,
  testp2__language__enum_values_by_number,
  3,
  testp2__language__enum_values_by_name,
  1,
  testp2__language__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
